spring:
   datasource:
    url: jdbc:sqlserver://wegrowsq.database.windows.net:1433;database=wegrowDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: wegrowadmin
    password: Password@123
   jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
     dialect: org.hibernate.dialect.SQLServer2012Dialect
  
server:
 port: 8080	 		
 
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR